AKS Baseline Multi Region - Customize manifests to pull images from the private ACR
mspnp/aks-baseline-multi-region pull request #28
Opened 2021-07-28 21:18 UTC by magrande

2021-07-28 21:24 UTC, ckittel requested changes
Things I would have expected to see but don't

* A change to the Azure Policies to disallow these specific public container images
* A change to Azure Firewall rules to no longer support pulling these specific public container images
* A git add/commit/push for the change made to the kustomization yaml file

The stuff you have here looks good (only one tiny item below)

2021-07-28 21:24 UTC, ckittel commented on cluster-stamp.json
> +                "[resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', variables('clusterControlPlaneIdentityName'))]",
Do you still need this `dependsOn` entry?

2021-07-29 20:18 UTC, ckittel commented
Just one open item, and that's the `sed` command needs to be updated to impact both `kustomization.yaml` files now.

2021-07-29 20:44 UTC, magrande commented
> Just one open item, and that's the `sed` command needs to be updated to impact both `kustomization.yaml` files now.

Fixed and tested !

2021-07-29 20:51 UTC, ckittel approved these changes
Cool, everything but traefik.  I'll add a backlog item to get that one in a future sprint.

2021-07-29 20:52 UTC, merged