Skabou patch 1
mspnp/aks-baseline-multi-region pull request #67
Opened 2022-09-19 19:16 UTC by skabou

Fix broken link as mentioned in #66 .  Follows pattern of aks-baseline.

2022-09-19 20:26 UTC, ckittel requested changes

2022-09-19 20:26 UTC, ckittel commented on README.md
> +## :broom: Clean up resources
Can you put this at line 65 instead?  That's where the cleanup all resources link is.  OR delete line 65 so we only have one "step 11" instead of two in this section.

2022-09-19 20:35 UTC, skabou commented on README.md
> +## :broom: Clean up resources
@ckittel Good catch.  Updated.

2022-09-20 14:55 UTC, ckittel reviewed
LGTM!  👍

2022-09-20 14:55 UTC, ckittel approved these changes

2022-09-20 14:55 UTC, merged