Populate variables
mspnp/aks-baseline-multi-region pull request #70
Opened 2022-12-07 12:00 UTC by v-fearam

#21 
Add procedure to populate variables on step 4 of the validation content

On step 4 of the 10-validation.md content, we instruct to open a new terminal

2022-12-13 20:21 UTC, ckittel requested changes

2022-12-13 20:21 UTC, ckittel commented on docs/deploy/10-validation.md
> +   APPGW_FQDN_BU0001A0042_04=$(az deployment group show -g rg-bu0001a0042-04 -n cluster-stamp --query properties.outputs.agwName.value -o tsv)
Why does the variable names have FQDN in them if they are just being populated by the resource names?  The FWDN value is `properties.outputs.agwName.value` but it looks like you have (and we need) `properties.outputs.agwName.value` here.  The variable name should likely be updated to reflect this.

Alos, why are we doing this when we populate them few lines above (see line 14 and 15)?  (which also is using FQDN instead of name)

I'm confused at what problem you're solving here, but let's make sure we take the time to rename the variable to something more appropriate.  Thanks!

2022-12-13 23:36 UTC, v-fearam commented on docs/deploy/10-validation.md
> +   APPGW_FQDN_BU0001A0042_04=$(az deployment group show -g rg-bu0001a0042-04 -n cluster-stamp --query properties.outputs.agwName.value -o tsv)
Point 1: 
_Also, why are we doing this when we populate them few lines above (see line 14 and 15)? (which also is using FQDN instead of name)_
That is the issue #21 which I'm solving, in line 40 said "Open another terminal", so the context is not on the new terminal and that why need to be populated again.

Point 2:  
_why does the variable names have FQDN in them if they are just being populated by the resource names?_
I don't have idea, It was on that way. I only keep in the way that it was and populated the variables in the new terminal. Very simple change.
Let me know which name is good for you and I will change.

2022-12-14 14:18 UTC, ckittel commented on docs/deploy/10-validation.md
> +   APPGW_FQDN_BU0001A0042_04=$(az deployment group show -g rg-bu0001a0042-04 -n cluster-stamp --query properties.outputs.agwName.value -o tsv)
Point 1, ah, yes, missed that!  thank you for pointing that out..

Point 2. Yeah, let's change the name in both situations to something more accurate.  They can remain both using the same name (even though that is what was causing my confusion), but go ahead and use a more accurate name.

2022-12-14 16:11 UTC, ckittel commented on github-workflow/aks-deploy.yaml
> +          APPGW_BU0001A0042_03=$(az deployment group show -g rg-enterprise-networking-spokes -n spoke-BU0001A0042-03 --query properties.outputs.appGwFqdn.value -o tsv)
Why did you change this one?  This was a FQDN before.

2022-12-14 16:13 UTC, ckittel commented on docs/deploy/10-validation.md
> +   APPGW_FQDN_BU0001A0042_04=$(az deployment group show -g rg-bu0001a0042-04 -n cluster-stamp --query properties.outputs.agwName.value -o tsv)
For this local change, resolved.  But this opened up a new issue @ https://github.com/mspnp/aks-baseline-multi-region/pull/70#pullrequestreview-1217764477

2022-12-14 16:43 UTC, v-fearam commented on github-workflow/aks-deploy.yaml
> +          APPGW_BU0001A0042_03=$(az deployment group show -g rg-enterprise-networking-spokes -n spoke-BU0001A0042-03 --query properties.outputs.appGwFqdn.value -o tsv)
I didn't realize. Good catch, I changed all the occurrences. Reverting

2022-12-14 16:52 UTC, ckittel approved these changes
LGTM!  :shipit:

2022-12-14 17:07 UTC, merged