GitHub Action Azure Federated Identity
mspnp/aks-baseline-multi-region pull request #72
Opened 2022-12-12 17:23 UTC by v-fearam

2022-12-13 19:58 UTC, ckittel requested changes
Lookin good!  Here's some first-round feedback for ya.

2022-12-13 19:58 UTC, ckittel commented on docs/deploy/06-aks-cluster.md
> +        az deployment group create -g rg-bu0001a0042-shared -f ghaction-federated-identity.bicep -p gitAccount="$GITHUB_ACCOUNT_NAME"
Can you instead just add this to step 3's bicep file?  Why make this something else?  Then it will already be in place for this step.

Also, has already been captured as `$GITHUB_USER_NAME_AKS_MRB` so no need to get it again.  So you can provide that as a parameter in step 3's deployment.

2022-12-13 19:58 UTC, ckittel commented on docs/deploy/06-aks-cluster.md
> +        export APP_ID=$(az deployment group show -g rg-bu0001a0042-shared -n ghaction-federated-identity --query 'properties.outputs.clientId.value' -o tsv)
Suggestion: Be more clear instead of `APP_ID` give it a meaningful name like `GitHubFederatedIdentity_ClientID`

2022-12-13 19:58 UTC, ckittel commented on docs/deploy/06-aks-cluster.md
> +        echo SUBSCRIPTION_ID: $SUBSCRIPTION_ID
`jq` should not be a dependency.  Otherwise we need to list that on the dependency page, and that would be a pretty big hammer for such little usage.  Please use `--query` instead.

2022-12-13 19:58 UTC, ckittel commented on docs/deploy/06-aks-cluster.md
> +        gh secret set AZURE_CLIENT_ID -b"${APP_ID}"  --repo $GITHUB_ACCOUNT_NAME/aks-baseline-multi-region
Use the already existing `$GITHUB_USER_NAME_AKS_MRB` for these repo names here and below.  And nice touch adding that in to be explicit!

2022-12-13 19:58 UTC, ckittel commented on ghaction-federated-identity.bicep
> +}
Where are the permissions being set for this user?  I didn't see them manually being set (nor should they), when you move this over to the shared deployment, you can add those required role assignments in there.

2022-12-13 19:58 UTC, ckittel commented on ghaction-federated-identity.bicep
> +output principalId string = ghActionFederatedIdentity.properties.principalId
Probably only need client ID returned, right?

2022-12-13 19:58 UTC, ckittel commented on github-workflow/aks-deploy.yaml
> +      contents: read
formatting looks off here for yaml?  Too much indent?

2022-12-14 10:53 UTC, v-fearam commented on docs/deploy/06-aks-cluster.md
> +        az deployment group create -g rg-bu0001a0042-shared -f ghaction-federated-identity.bicep -p gitAccount="$GITHUB_ACCOUNT_NAME"
I didn't add to other deploy file because this is a resource which is only needed because we are using gitHubAction, it is not part of the aks baseline narrative. I thought that it would be better keep isolated.   
We can move to az cli instructions or move some pre-existent deploy file (This reference implementation still use arm, it is the first bicep).   
Good catch about the variable, it was changed https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/7e97c8836b20dfcf1244ac0eea6f46ba075cbd61

2022-12-14 10:53 UTC, v-fearam commented on docs/deploy/06-aks-cluster.md
> +        export APP_ID=$(az deployment group show -g rg-bu0001a0042-shared -n ghaction-federated-identity --query 'properties.outputs.clientId.value' -o tsv)
done https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/7e97c8836b20dfcf1244ac0eea6f46ba075cbd61

2022-12-14 10:54 UTC, v-fearam commented on docs/deploy/06-aks-cluster.md
> +        echo SUBSCRIPTION_ID: $SUBSCRIPTION_ID
done https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/7e97c8836b20dfcf1244ac0eea6f46ba075cbd61

2022-12-14 10:54 UTC, v-fearam commented on docs/deploy/06-aks-cluster.md
> +        gh secret set AZURE_CLIENT_ID -b"${APP_ID}"  --repo $GITHUB_ACCOUNT_NAME/aks-baseline-multi-region
done https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/7e97c8836b20dfcf1244ac0eea6f46ba075cbd61

2022-12-14 11:01 UTC, v-fearam commented on ghaction-federated-identity.bicep
> +}
Where are the permissions being set for this user? It was not changed in this PR https://github.com/mspnp/aks-baseline-multi-region/pull/72/files#diff-3657143ea58b25a778a8cefe6a12f30b9ec956e3423d6c575f1c48c9ecdbd986L69-L74
Why?
Because I don't have permissions to assign roles at subscription level and  fail the execution for me. So, I decided create the resource and then keep the permission as before .
The couple of az cli instruction could be  executed for another person which is able execute the role assignment at subscription level.  
We could change, but that are de reasons

2022-12-14 11:01 UTC, v-fearam commented on ghaction-federated-identity.bicep
> +output principalId string = ghActionFederatedIdentity.properties.principalId
done https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/7e97c8836b20dfcf1244ac0eea6f46ba075cbd61

2022-12-14 11:01 UTC, v-fearam commented on github-workflow/aks-deploy.yaml
> +      contents: read
done https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/7e97c8836b20dfcf1244ac0eea6f46ba075cbd61

2022-12-14 14:27 UTC, ckittel commented on ghaction-federated-identity.bicep
> +}
Ah.  That's a tough one.  The same person that deploys the bicep is expected to be the person that runs the steps as well, since we have a pre-req of user access admin on the subscription.  I think we can leave the manual application of permissions as-is, even though that adds extra steps for most people.  Thanks for explaining.  If we move the creation of this out, you'll need to update the step title then for this as it's not about creating the creds, just assigning standing permissions.

2022-12-14 14:28 UTC, ckittel commented on docs/deploy/06-aks-cluster.md
> +        gh secret set AZURE_CLIENT_ID -b"${APP_ID}"  --repo $GITHUB_ACCOUNT_NAME/aks-baseline-multi-region
You still have ":warning: Set your GitHub Account" in there.

2022-12-14 14:36 UTC, ckittel commented on docs/deploy/06-aks-cluster.md
> +        az deployment group create -g rg-bu0001a0042-shared -f ghaction-federated-identity.bicep -p gitAccount="$GITHUB_ACCOUNT_NAME"
Thanks for your comment on teams, let's go ahead and just add it to the shared json ARM file.  When you're porting it over, I'd suggest a parameter name of `gitHubAccountName`.  That'll match our variable name and will disambiguate between a git username and a GitHub account.

2022-12-14 17:05 UTC, v-fearam commented on docs/deploy/06-aks-cluster.md
> +        az deployment group create -g rg-bu0001a0042-shared -f ghaction-federated-identity.bicep -p gitAccount="$GITHUB_ACCOUNT_NAME"
https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/5438bbbc093577ad9f260a073e0b7ddcdde81d86

2022-12-14 17:06 UTC, v-fearam commented on docs/deploy/06-aks-cluster.md
> +        export APP_ID=$(az deployment group show -g rg-bu0001a0042-shared -n ghaction-federated-identity --query 'properties.outputs.clientId.value' -o tsv)
https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/5438bbbc093577ad9f260a073e0b7ddcdde81d86

2022-12-14 17:06 UTC, v-fearam commented on docs/deploy/06-aks-cluster.md
> +        gh secret set AZURE_CLIENT_ID -b"${APP_ID}"  --repo $GITHUB_ACCOUNT_NAME/aks-baseline-multi-region
https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/5438bbbc093577ad9f260a073e0b7ddcdde81d86

2022-12-14 17:20 UTC, ckittel requested changes
Looking really good.  Couple items here yet.

2022-12-14 17:20 UTC, ckittel commented on docs/deploy/03-cluster-prerequisites.md
> +az deployment group create -g rg-bu0001a0042-shared -f shared-svcs-stamp.json -p location=eastus2 gitHubAccountName=$GITHUB_USER_NAME_AKS_MRB
Please add the managed identity with GitHub federation to the resource list in the table above.

2022-12-14 17:20 UTC, ckittel commented on docs/deploy/06-aks-cluster.md
> +    1. Assign standard permission on the subccription for the identity which will use the [GitHub CD workflow](https://learn.microsoft.com/azure/developer/github/connect-from-azure).
```suggestion
    1. Assign required permissions to the [GitHub workflow's](https://learn.microsoft.com/azure/developer/github/connect-from-azure) managed (federated) identity.
```

2022-12-14 17:20 UTC, ckittel commented on docs/deploy/06-aks-cluster.md
> +        # Getting the deployed identity to assign standard permissions
```suggestion
        # Get the managed identity to assign necessary deployment permissions
```

2022-12-14 17:20 UTC, ckittel commented on docs/deploy/06-aks-cluster.md
> +    1. Create secrets in your GitHub repository.
```suggestion
    1. Create federated identity secrets in your GitHub repository.
```

2022-12-14 17:20 UTC, ckittel commented on docs/deploy/06-aks-cluster.md
>          > :bulb: Use the content from the `sp.json` file.
what sp.json?

2022-12-14 17:20 UTC, ckittel commented on shared-svcs-stamp.json
> +        },
To align with our other implementations, can you please make this a child resource of the `userAssignedIdentities` resource.

2022-12-14 17:35 UTC, v-fearam commented on docs/deploy/06-aks-cluster.md
>          > :bulb: Use the content from the `sp.json` file.
This line needs to be deleted. Good Point.

2022-12-14 18:03 UTC, v-fearam commented on docs/deploy/03-cluster-prerequisites.md
> +az deployment group create -g rg-bu0001a0042-shared -f shared-svcs-stamp.json -p location=eastus2 gitHubAccountName=$GITHUB_USER_NAME_AKS_MRB
https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/0cf85dcb8cb79aa133564b7cd623db9f464e24d5

2022-12-14 18:03 UTC, v-fearam commented on docs/deploy/06-aks-cluster.md
>          > :bulb: Use the content from the `sp.json` file.
https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/0cf85dcb8cb79aa133564b7cd623db9f464e24d5

2022-12-14 18:03 UTC, v-fearam commented on shared-svcs-stamp.json
> +        },
https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/0cf85dcb8cb79aa133564b7cd623db9f464e24d5

2022-12-14 18:13 UTC, ckittel requested changes

2022-12-14 18:13 UTC, ckittel commented on shared-svcs-stamp.json
> +                    "name": "[format('{0}/{1}', 'ghActionFederatedIdentity', 'ghActionFederatedIdentity')]",
The purpose of moving to a child resource is to avoid the complexity of naming them, in addition to showing clear intent/relationship.

```suggestion
                    "type": "federatedIdentityCredentials",
                    "apiVersion": "2022-01-31-preview",
                    "name": "ghActionFederatedIdentity",
```

2022-12-14 18:13 UTC, ckittel commented on shared-svcs-stamp.json
> +                "description": "Your git account where the repo is your cloned."
```suggestion
                "description": "Your GitHub account where the repo is cloned."
```

2022-12-14 18:13 UTC, ckittel commented on shared-svcs-stamp.json
> +                "description": "The branch used for run your workflow. For Jobs not tied to an environment, include the ref path for branch/tag based on the ref path used for triggering the workflow:
```suggestion
                "description": "The branch used to run your workflow. For Jobs not tied to an environment, include the ref path for branch/tag based on the ref path used for triggering the workflow: repo:< Organization/Repository >:ref:< ref path>"
```

2022-12-14 18:24 UTC, v-fearam commented on shared-svcs-stamp.json
> +                    "name": "[format('{0}/{1}', 'ghActionFederatedIdentity', 'ghActionFederatedIdentity')]",
https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/b0519e5207a51fa055658eff50be0ecb93c1d985

2022-12-14 18:24 UTC, v-fearam commented on shared-svcs-stamp.json
> +                "description": "Your git account where the repo is your cloned."
https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/b0519e5207a51fa055658eff50be0ecb93c1d985

2022-12-14 18:24 UTC, v-fearam commented on shared-svcs-stamp.json
> +                "description": "The branch used for run your workflow. For Jobs not tied to an environment, include the ref path for branch/tag based on the ref path used for triggering the workflow:
https://github.com/mspnp/aks-baseline-multi-region/pull/72/commits/b0519e5207a51fa055658eff50be0ecb93c1d985

2022-12-14 20:15 UTC, ckittel approved these changes
LGTM, thanks.  Nice little improvement for sure.

2022-12-14 22:09 UTC, merged