feat (cluster): [day2-ops] node update configuration
mspnp/aks-baseline-multi-region pull request #84
Opened 2024-03-22 15:42 UTC by ferantivero

- remove Kubernetes Reboot Daemon (Kured)
- enable node update channel for K8s version automatic upgrades (node-image)
- enable node os level update channel for OS security NodeImage automatic upgrades
- add maintenance windows for k8s version and os level upgrades
- add some initial guidance to the docs

2024-03-22 19:31 UTC, ckittel commented on cluster-stamp.json
> +              "startTime": "21:00"
I know you don't have a formal review yet, but I was thinking how this scenario this might be a GREAT example for multi-cluster where you can set one cluster on Tuesday and the other on Wednesday.  Really would help show a rolling patch process.

2024-03-22 19:57 UTC, ferantivero commented on cluster-stamp.json
> +              "startTime": "21:00"
I like this idea, this would just require to parametrize the "day".

While I'd love to address this as proposed, IDK why I would've expected the team to suggest moving this multi region cluster to be updated "manually". The rationale for this is that node images roll out might take up to a few  few weeks to be in sync in all regions. Paired regions shouldn't take that much, I guess.

2024-03-22 20:35 UTC, ckittel commented
Also, sorry, just landed a conversion of that first shared services JSON file to be bicep.  Merge conflict :(

2024-03-22 20:38 UTC, ferantivero commented
> Also, sorry, just landed a conversion of that first shared services JSON file to be bicep. Merge conflict :(

no worries at all. Moving this to bicep is a quick and easy thing to do.

2024-04-22 15:23 UTC, skabou requested changes
Looks good - What about the two shared-svcs-stamp files?

2024-04-22 15:23 UTC, skabou commented on docs/deploy/06-aks-cluster.md
> +       > Node images in region 1 and 2 could defer if recent shipped images didn't arrive to a particular region. Consider as part of day2 activities monitoring the release status by regions at [AKS-
```suggestion
       > Node images in regions 1 and 2 could differ if recently shipped images didn't arrive in a particular region. As part of day2 activities, consider monitoring the release status by region at [AKS-Release-Tracker](https://releases.aks.azure.com/). Releases can take up to two weeks to roll out to all regions from the initial time of shipping due to Azure Safe Deployment Practices (SDP). If your AKS node images in regions 1 and 2 are required to be on the same version you should consider updating the node images manually.
```

2024-04-22 15:24 UTC, skabou commented on docs/deploy/09-workload.md
Nice catch!

2024-04-22 15:25 UTC, skabou commented on docs/deploy/09-workload.md
> +   kubectl apply -f ./workload/aspnetapp-canary.yaml --context $AKS_CLUSTER_NAME_BU0001A0042_04_AKS_MRB
Nice catch!

2024-04-22 19:07 UTC, ferantivero commented
> Looks good - What about the two shared-svcs-stamp files?

somehow it got spilled off https://github.com/mspnp/aks-baseline-multi-region/pull/84/commits/adc750f43682b8f932691178683412b803a04ba9

2024-04-22 19:24 UTC, skabou approved these changes
LGTM 🚀

2024-04-23 19:03 UTC, merged